// Integration test: verify character_data.hpp loads animations.json correctly
// Build: c++ -std=c++23 -I include -I build/macos-debug/_deps/json-src/include -I build/macos-debug/_deps/glm-src -I build/macos-debug/_deps/stb-src tests/test_character_data.cpp src/engine/character_data.cpp src/engine/tilemap.cpp -o build/test_character_data

#include "vulkan_game/engine/character_data.hpp"
#include <cassert>
#include <cstdio>

int main() {
    using namespace vulkan_game;

    // Test 1: Load existing test animations.json
    {
        auto result = load_character_anims("assets/characters/test/animations.json");
        assert(result.has_value() && "Should load test animations.json");

        auto& data = *result;
        assert(data.tileset.tile_width == 16);
        assert(data.tileset.tile_height == 16);
        assert(data.tileset.columns == 4);
        assert(data.tileset.sheet_width == 64);
        assert(data.tileset.sheet_height == 192);
        assert(data.clips.size() == 12 && "Should have 12 clips (3 states x 4 dirs)");

        // Check first clip
        assert(data.clips[0].name == "idle_down");
        assert(data.clips[0].looping == true);
        assert(data.clips[0].frames.size() == 4);
        assert(data.clips[0].frames[0].tile_id == 0);
        assert(data.clips[0].frames[0].duration > 0.29f && data.clips[0].frames[0].duration < 0.31f);

        // Check last clip
        assert(data.clips[11].name == "run_up");
        assert(data.clips[11].frames[0].tile_id == 44);
        assert(data.clips[11].frames[0].duration > 0.06f && data.clips[11].frames[0].duration < 0.08f);

        printf("PASS: Test 1 - Load test animations.json\n");
    }

    // Test 2: Non-existent file returns nullopt
    {
        auto result = load_character_anims("assets/characters/nonexistent/animations.json");
        assert(!result.has_value() && "Should return nullopt for missing file");
        printf("PASS: Test 2 - Missing file returns nullopt\n");
    }

    // Test 3: Load protagonist animations.json (generated by atlas assembler)
    {
        auto result = load_character_anims("assets/characters/protagonist/animations.json");
        assert(result.has_value() && "Should load protagonist animations.json");

        auto& data = *result;
        assert(data.tileset.tile_width == 128);
        assert(data.tileset.tile_height == 128);
        assert(data.tileset.columns == 4);
        assert(data.tileset.sheet_width == 512);
        assert(data.tileset.sheet_height == 1536);
        assert(data.clips.size() == 12);

        printf("PASS: Test 3 - Load protagonist animations.json\n");
    }

    printf("\nAll tests passed!\n");
    return 0;
}
